#pragma once
#include <string>
#include <vector>
#include <list>
#include <deque>
#include <map>
#include <sstream>
#include <fstream>
#include <functional>
#include <algorithm>
#include <cassert>
#include <memory>